services:
  container:
    image: llmcordplus-container
    container_name: llmcordplus
    build: .
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./config.yaml:/app/config.yaml